site_name: Quimanima
site_url: https://quimanima.readthedocs.io/en/latest/
site_description: "QUIMANIMA: animações computacionais para química do ensino médio"
repo_url: https://github.com/quimanima/quimanima

theme: 
  name: material
  language: pt

nav:
  - Inicial: index.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.tilde
